module.exports.htmlGlobalProps = [
  "accesskey",
  "autocapitalize",
  "class",
  "contenteditable",
  "contextmenu",
  // "data-*",
  "dir",
  "draggable",
  "dropzone",
  "hidden",
  "id",
  "is",
  "itemid",
  "itemprop",
  "itemref",
  "itemscope",
  "itemtype",
  "lang",
  "slot",
  "spellcheck",
  "style",
  "tabindex",
  "title",
  "translate",
];

module.exports.htmlPropsToElementsMap = {
  accept: ["form", "input"],
  "accept-charset": ["form"],
  action: ["form"],
  align: [
    "applet",
    "caption",
    "col",
    "colgroup",
    "hr",
    "iframe",
    "img",
    "table",
    "tbody",
    "td",
    "tfoot",
    "th",
    "thead",
    "tr",
  ],
  alt: ["applet", "area", "img", "input"],
  async: ["script"],
  autocomplete: ["form", "input", "textarea"],
  autofocus: ["button", "input", "keygen", "select", "textarea"],
  autoplay: ["audio", "video"],
  buffered: ["audio", "video"],
  challenge: ["keygen"],
  charset: ["meta", "script"],
  checked: ["command", "input"],
  cite: ["blockquote", "del", "ins", "q"],
  code: ["applet"],
  codebase: ["applet"],
  cols: ["textarea"],
  colspan: ["td", "th"],
  content: ["meta"],
  controls: ["audio", "video"],
  coords: ["area"],
  crossorigin: ["audio", "img", "link", "script", "video"],
  data: ["object"],
  datetime: ["del", "ins", "time"],
  default: ["track"],
  defer: ["script"],
  dirname: ["input", "textarea"],
  disabled: [
    "button",
    "command",
    "fieldset",
    "input",
    "keygen",
    "optgroup",
    "option",
    "select",
    "textarea",
  ],
  download: ["a", "area"],
  enctype: ["form"],
  for: ["label", "output"],
  form: [
    "button",
    "fieldset",
    "input",
    "keygen",
    "label",
    "meter",
    "object",
    "output",
    "progress",
    "select",
    "textarea",
  ],
  formaction: ["input", "button"],
  headers: ["td", "th"],
  height: ["canvas", "embed", "iframe", "img", "input", "object", "video"],
  high: ["meter"],
  href: ["a", "area", "base", "link"],
  hreflang: ["a", "area", "link"],
  "http-equiv": ["meta"],
  icon: ["command"],
  integrity: ["link", "script"],
  ismap: ["img"],
  keytype: ["keygen"],
  kind: ["track"],
  label: ["track"],
  language: ["script"],
  list: ["input"],
  loop: ["audio", "bgsound", "marquee", "video"],
  low: ["meter"],
  manifest: ["html"],
  max: ["input", "meter", "progress"],
  maxlength: ["input", "textarea"],
  minlength: ["input", "textarea"],
  media: ["a", "area", "link", "source", "style"],
  method: ["form"],
  min: ["input", "meter"],
  multiple: ["input", "select"],
  muted: ["audio", "video"],
  name: [
    "button",
    "form",
    "fieldset",
    "iframe",
    "input",
    "keygen",
    "object",
    "output",
    "select",
    "textarea",
    "map",
    "meta",
    "param",
  ],
  novalidate: ["form"],
  open: ["details"],
  optimum: ["meter"],
  pattern: ["input"],
  ping: ["a", "area"],
  placeholder: ["input", "textarea"],
  poster: ["video"],
  preload: ["audio", "video"],
  radiogroup: ["command"],
  readonly: ["input", "textarea"],
  rel: ["a", "area", "link"],
  required: ["input", "select", "textarea"],
  reversed: ["ol"],
  rows: ["textarea"],
  rowspan: ["td", "th"],
  sandbox: ["iframe"],
  scope: ["th"],
  scoped: ["style"],
  selected: ["option"],
  shape: ["a", "area"],
  size: ["input", "select"],
  sizes: ["link", "img", "source"],
  span: ["col", "colgroup"],
  src: [
    "audio",
    "embed",
    "iframe",
    "img",
    "input",
    "script",
    "source",
    "track",
    "video",
  ],
  srcdoc: ["iframe"],
  srclang: ["track"],
  srcset: ["img"],
  start: ["ol"],
  step: ["input"],
  summary: ["table"],
  target: ["a", "area", "base", "form"],
  type: [
    "button",
    "input",
    "command",
    "embed",
    "object",
    "script",
    "source",
    "style",
    "menu",
  ],
  usemap: ["img", "input", "object"],
  value: ["button", "option", "input", "li", "meter", "progress", "param"],
  width: ["canvas", "embed", "iframe", "img", "input", "object", "video"],
  wrap: ["textarea"],
};

module.exports.htmlLegacyProps = ["bgcolor", "border", "color"];

module.exports.legacyHTMLPropsToElementsMap = {
  bgcolor: [
    "body",
    "col",
    "colgroup",
    "marquee",
    "table",
    "tbody",
    "tfoot",
    "td",
    "th",
    "tr",
  ],
  border: ["img", "object", "table"],
  color: ["basefont", "font", "hr"],
};

module.exports.htmlObsoleteElements = [
  "acronym",
  "applet",
  "basefont",
  "bgsound",
  "big",
  "blink",
  "center",
  "command",
  "dir",
  "element",
  "font",
  "image",
  "listing",
  "marquee",
  "multicol",
  "nextid",
  "nobr",
  "noembed",
  "noframes",
  "plaintext",
  "spacer",
  "strike",
  "tt",
  "xmp",
];

module.exports.htmlDeprecatedElements = [
  "content",
  "frame",
  "frameset",
  "isindex",
  "keygen",
  "menuitem",
  "shadow",
];

module.exports.htmlNonStandardElements = [
  "bgsound",
  "image",
  "multicol",
  "nobr",
  "noembed",
];

module.exports.htmlExperimentalElements = ["dialog", "hgroup"];

const common1 = [
  "a",
  "altGlyph",
  "animate",
  "animateColor",
  "circle",
  "clipPath",
  "defs",
  "ellipse",
  "feBlend",
  "feColorMatrix",
  "feComponentTransfer",
  "feComposite",
  "feConvolveMatrix",
  "feDiffuseLighting",
  "feDisplacementMap",
  "feFlood",
  "feGaussianBlur",
  "feImage",
  "feMerge",
  "feMorphology",
  "feOffset",
  "feSpecularLighting",
  "feTile",
  "feTurbulence",
  "filter",
  "font",
  "foreignObject",
  "g",
  "glyph",
  "glyphRef",
  "image",
  "line",
  "linearGradient",
  "marker",
  "mask",
  "missing-glyph",
  "path",
  "pattern",
  "polygon",
  "polyline",
  "radialGradient",
  "rect",
  "stop",
  "svg",
  "switch",
  "symbol",
  "text",
  "textPath",
  "tref",
  "tspan",
  "use",
];

module.exports.svgElements = [
  "a",
  "altGlyph",
  "animate",
  "animateColor",
  "animateMotion",
  "animateTransform",
  "animation",
  "audio",
  "canvas",
  "circle",
  "clipPath",
  "color-profile",
  "cursor",
  "defs",
  "desc",
  "discard",
  "ellipse",
  "feBlend",
  "feColorMatrix",
  "feComponentTransfer",
  "feComposite",
  "feConvolveMatrix",
  "feDiffuseLighting",
  "feDisplacementMap",
  "feDistantLight",
  "feDropShadow",
  "feFlood",
  "feFuncA",
  "feFuncB",
  "feFuncG",
  "feFuncR",
  "feGaussianBlur",
  "feImage",
  "feMerge",
  "feMergeNode",
  "feMorphology",
  "feOffset",
  "fePointLight",
  "feSpecularLighting",
  "feSpotLight",
  "feTile",
  "feTurbulence",
  "filter",
  "font",
  "font-face",
  "font-face-format",
  "font-face-name",
  "font-face-uri",
  "foreignObject",
  "g",
  "glyph",
  "glyphRef",
  "handler",
  "hatch",
  "hatchpath",
  "hkern",
  "iframe",
  "image",
  "line",
  "linearGradient",
  "listener",
  "marker",
  "mask",
  "mesh",
  "meshgradient",
  "meshpatch",
  "meshrow",
  "metadata",
  "missing-glyph",
  "mpath",
  "path",
  "pattern",
  "polygon",
  "polyline",
  "prefetch",
  "radialGradient",
  "rect",
  "script",
  "set",
  "solidcolor",
  "stop",
  "style",
  "svg",
  "switch",
  "symbol",
  "tbreak",
  "text",
  "textArea",
  "textPath",
  "title",
  "tref",
  "tspan",
  "unknown",
  "use",
  "video",
  "view",
  "vkern",
];

module.exports.svgPropsToElementsMap = {
  "alignment-baseline": common1,
  "baseline-shift": common1,
  clip: common1,
  "clip-path": common1,
  "clip-rule": common1,
  color: common1,
  "color-interpolation": common1,
  "color-interpolation-filters": common1,
  "color-profile": common1,
  "color-rendering": common1,
  cursor: common1,
  direction: common1,
  display: common1,
  "dominant-baseline": common1,
  download: ["a"],
  "enable-background": common1,
  externalResourcesRequired: [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "circle",
    "clipPath",
    "cursor",
    "defs",
    "ellipse",
    "feImage",
    "filter",
    "font",
    "font-face",
    "font-face-uri",
    "foreignObject",
    "g",
    "handler",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "mpath",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "script",
    "set",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
    "video",
    "view",
  ],
  fill: [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "circle",
    "clipPath",
    "defs",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "set",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
    "video",
  ],
  "fill-opacity": common1,
  "fill-rule": common1,
  filter: common1,
  "flood-color": common1,
  "flood-opacity": common1,
  focusHighlight: [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  focusable: [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "font-family": [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "circle",
    "clipPath",
    "defs",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "font-face",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
  ],
  "font-size": [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "circle",
    "clipPath",
    "defs",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "font-face",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
  ],
  "font-size-adjust": common1,
  "font-stretch": [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "circle",
    "clipPath",
    "defs",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "font-face",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
  ],
  "font-style": [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "circle",
    "clipPath",
    "defs",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "font-face",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
  ],
  "font-variant": [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "circle",
    "clipPath",
    "defs",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "font-face",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
  ],
  "font-weight": [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "circle",
    "clipPath",
    "defs",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "font-face",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "tref",
    "tspan",
    "use",
  ],
  "glyph-orientation-horizontal": common1,
  "glyph-orientation-vertical": common1,
  href: [
    "a",
    "animate",
    "animateMotion",
    "animateTransform",
    "cursor",
    "discard",
    "feImage",
    "hatch",
    "image",
    "linearGradient",
    "mesh",
    "meshgradient",
    "mpath",
    "pattern",
    "radialGradient",
    "script",
    "set",
    "textPath",
    "use",
  ],
  hreflang: ["a"],
  "image-rendering": common1,
  kerning: common1,
  "letter-spacing": common1,
  "lighting-color": common1,
  "marker-end": common1,
  "marker-mid": common1,
  "marker-start": common1,
  mask: common1,
  "nav-down": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-down-left": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-down-right": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-left": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-next": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-prev": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-right": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-up": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-up-left": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  "nav-up-right": [
    "a",
    "animation",
    "circle",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "tspan",
    "use",
    "video",
  ],
  opacity: common1,
  overflow: common1,
  "pointer-events": common1,
  requiredExtensions: [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "canvas",
    "circle",
    "clipPath",
    "cursor",
    "defs",
    "desc",
    "discard",
    "ellipse",
    "foreignObject",
    "g",
    "iframe",
    "image",
    "line",
    "mask",
    "mesh",
    "metadata",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "rect",
    "set",
    "svg",
    "switch",
    "tbreak",
    "text",
    "textArea",
    "textPath",
    "title",
    "tref",
    "tspan",
    "unknown",
    "use",
    "video",
  ],
  requiredFeatures: [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "circle",
    "clipPath",
    "cursor",
    "defs",
    "desc",
    "discard",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "mask",
    "metadata",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "rect",
    "set",
    "svg",
    "switch",
    "tbreak",
    "text",
    "textArea",
    "textPath",
    "title",
    "tref",
    "tspan",
    "use",
    "video",
  ],
  requiredFonts: [
    "a",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "circle",
    "desc",
    "discard",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "metadata",
    "path",
    "polygon",
    "polyline",
    "rect",
    "set",
    "switch",
    "tbreak",
    "text",
    "textArea",
    "title",
    "tspan",
    "use",
    "video",
  ],
  requiredFormats: [
    "a",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "circle",
    "desc",
    "discard",
    "ellipse",
    "foreignObject",
    "g",
    "image",
    "line",
    "metadata",
    "path",
    "polygon",
    "polyline",
    "rect",
    "set",
    "switch",
    "tbreak",
    "text",
    "textArea",
    "title",
    "tspan",
    "use",
    "video",
  ],
  "shape-rendering": common1,
  "stop-color": common1,
  "stop-opacity": common1,
  stroke: common1,
  "stroke-dasharray": common1,
  "stroke-dashoffset": common1,
  "stroke-linecap": common1,
  "stroke-linejoin": common1,
  "stroke-miterlimit": common1,
  "stroke-opacity": common1,
  "stroke-width": common1,
  style: [
    "a",
    "altGlyph",
    "audio",
    "canvas",
    "circle",
    "clipPath",
    "defs",
    "desc",
    "ellipse",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDropShadow",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "font",
    "foreignObject",
    "g",
    "glyph",
    "glyphRef",
    "hatch",
    "hatchpath",
    "iframe",
    "image",
    "line",
    "linearGradient",
    "marker",
    "mask",
    "meshgradient",
    "meshpatch",
    "meshrow",
    "missing-glyph",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "radialGradient",
    "rect",
    "solidcolor",
    "stop",
    "svg",
    "switch",
    "symbol",
    "text",
    "textPath",
    "title",
    "tref",
    "tspan",
    "unknown",
    "use",
    "video",
  ],
  systemLanguage: [
    "a",
    "altGlyph",
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "canvas",
    "circle",
    "clipPath",
    "cursor",
    "defs",
    "desc",
    "discard",
    "ellipse",
    "foreignObject",
    "g",
    "iframe",
    "image",
    "line",
    "mask",
    "mesh",
    "metadata",
    "path",
    "pattern",
    "polygon",
    "polyline",
    "rect",
    "set",
    "svg",
    "switch",
    "tbreak",
    "text",
    "textArea",
    "textPath",
    "title",
    "tref",
    "tspan",
    "unknown",
    "use",
    "video",
  ],
  target: ["a", "listener"],
  "text-anchor": common1,
  "text-decoration": common1,
  "text-rendering": common1,
  transform: [
    "a",
    "animation",
    "circle",
    "clipPath",
    "defs",
    "ellipse",
    "foreignObject",
    "g",
    "hatch",
    "image",
    "line",
    "meshgradient",
    "path",
    "polygon",
    "polyline",
    "rect",
    "svg",
    "switch",
    "text",
    "textArea",
    "use",
    "video",
  ],
  type: [
    "a",
    "animateTransform",
    "audio",
    "feColorMatrix",
    "feFuncA",
    "feFuncB",
    "feFuncG",
    "feFuncR",
    "feTurbulence",
    "handler",
    "image",
    "meshgradient",
    "script",
    "style",
    "video",
  ],
  "unicode-bidi": common1,
  visibility: common1,
  "word-spacing": common1,
  "writing-mode": common1,
  dx: [
    "altGlyph",
    "feDropShadow",
    "feOffset",
    "glyphRef",
    "text",
    "tref",
    "tspan",
  ],
  dy: [
    "altGlyph",
    "feDropShadow",
    "feOffset",
    "glyphRef",
    "text",
    "tref",
    "tspan",
  ],
  format: ["altGlyph", "glyphRef"],
  glyphRef: ["altGlyph", "glyphRef"],
  rotate: ["altGlyph", "animateMotion", "hatch", "text", "tref", "tspan"],
  x: [
    "altGlyph",
    "animation",
    "cursor",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDropShadow",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "fePointLight",
    "feSpecularLighting",
    "feSpotLight",
    "feTile",
    "feTurbulence",
    "filter",
    "foreignObject",
    "glyphRef",
    "hatch",
    "image",
    "mask",
    "meshgradient",
    "pattern",
    "rect",
    "svg",
    "text",
    "textArea",
    "tref",
    "tspan",
    "use",
    "video",
  ],
  y: [
    "altGlyph",
    "animation",
    "cursor",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDropShadow",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "fePointLight",
    "feSpecularLighting",
    "feSpotLight",
    "feTile",
    "feTurbulence",
    "filter",
    "foreignObject",
    "glyphRef",
    "hatch",
    "image",
    "mask",
    "meshgradient",
    "pattern",
    "rect",
    "svg",
    "text",
    "textArea",
    "tref",
    "tspan",
    "use",
    "video",
  ],
  accumulate: ["animate", "animateColor", "animateMotion", "animateTransform"],
  additive: ["animate", "animateColor", "animateMotion", "animateTransform"],
  attributeName: ["animate", "animateColor", "animateTransform", "set"],
  attributeType: ["animate", "animateColor", "animateTransform", "set"],
  begin: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "discard",
    "set",
    "video",
  ],
  by: ["animate", "animateColor", "animateMotion", "animateTransform"],
  calcMode: ["animate", "animateColor", "animateMotion", "animateTransform"],
  dur: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "set",
    "video",
  ],
  end: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "set",
    "video",
  ],
  from: ["animate", "animateColor", "animateMotion", "animateTransform"],
  keySplines: ["animate", "animateColor", "animateMotion", "animateTransform"],
  keyTimes: ["animate", "animateColor", "animateMotion", "animateTransform"],
  max: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "set",
    "video",
  ],
  min: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "set",
    "video",
  ],
  repeatCount: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "set",
    "video",
  ],
  repeatDur: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "set",
    "video",
  ],
  restart: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "animation",
    "audio",
    "set",
    "video",
  ],
  to: ["animate", "animateColor", "animateMotion", "animateTransform", "set"],
  values: [
    "animate",
    "animateColor",
    "animateMotion",
    "animateTransform",
    "feColorMatrix",
  ],
  keyPoints: ["animateMotion"],
  origin: ["animateMotion"],
  path: ["animateMotion", "stop", "textPath"],
  height: [
    "animation",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDropShadow",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "foreignObject",
    "image",
    "mask",
    "pattern",
    "rect",
    "svg",
    "textArea",
    "use",
    "video",
  ],
  initialVisibility: ["animation", "video"],
  preserveAspectRatio: [
    "animation",
    "canvas",
    "feImage",
    "image",
    "marker",
    "pattern",
    "svg",
    "symbol",
    "video",
    "view",
  ],
  syncBehavior: ["animation", "audio", "video"],
  syncMaster: ["animation", "audio", "video"],
  syncTolerance: ["animation", "audio", "video"],
  width: [
    "animation",
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDropShadow",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
    "filter",
    "foreignObject",
    "image",
    "mask",
    "pattern",
    "rect",
    "svg",
    "textArea",
    "use",
    "video",
  ],
  cx: ["circle", "ellipse", "radialGradient"],
  cy: ["circle", "ellipse", "radialGradient"],
  pathLength: [
    "circle",
    "ellipse",
    "line",
    "path",
    "polygon",
    "polyline",
    "rect",
  ],
  r: ["circle", "radialGradient"],
  clipPathUnits: ["clipPath"],
  local: ["color-profile"],
  name: ["color-profile", "font-face-name"],
  "rendering-intent": ["color-profile"],
  rx: ["ellipse", "rect"],
  ry: ["ellipse", "rect"],
  in: [
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDropShadow",
    "feGaussianBlur",
    "feMergeNode",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
  ],
  in2: ["feBlend", "feComposite", "feDisplacementMap"],
  mode: ["feBlend"],
  result: [
    "feBlend",
    "feColorMatrix",
    "feComponentTransfer",
    "feComposite",
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feDisplacementMap",
    "feDropShadow",
    "feFlood",
    "feGaussianBlur",
    "feImage",
    "feMerge",
    "feMorphology",
    "feOffset",
    "feSpecularLighting",
    "feTile",
    "feTurbulence",
  ],
  k1: ["feComposite"],
  k2: ["feComposite"],
  k3: ["feComposite"],
  k4: ["feComposite"],
  operator: ["feComposite", "feMorphology"],
  bias: ["feConvolveMatrix"],
  divisor: ["feConvolveMatrix"],
  edgeMode: ["feConvolveMatrix", "feGaussianBlur"],
  kernelMatrix: ["feConvolveMatrix"],
  kernelUnitLength: [
    "feConvolveMatrix",
    "feDiffuseLighting",
    "feSpecularLighting",
  ],
  order: ["feConvolveMatrix"],
  preserveAlpha: ["feConvolveMatrix"],
  targetX: ["feConvolveMatrix"],
  targetY: ["feConvolveMatrix"],
  diffuseConstant: ["feDiffuseLighting"],
  surfaceScale: ["feDiffuseLighting", "feSpecularLighting"],
  scale: ["feDisplacementMap"],
  xChannelSelector: ["feDisplacementMap"],
  yChannelSelector: ["feDisplacementMap"],
  azimuth: ["feDistantLight"],
  elevation: ["feDistantLight"],
  stdDeviation: ["feDropShadow", "feGaussianBlur"],
  amplitude: ["feFuncA", "feFuncB", "feFuncG", "feFuncR"],
  exponent: ["feFuncA", "feFuncB", "feFuncG", "feFuncR"],
  intercept: ["feFuncA", "feFuncB", "feFuncG", "feFuncR"],
  offset: ["feFuncA", "feFuncB", "feFuncG", "feFuncR", "hatchpath", "stop"],
  slope: ["feFuncA", "feFuncB", "feFuncG", "feFuncR", "font-face"],
  tableValues: ["feFuncA", "feFuncB", "feFuncG", "feFuncR"],
  crossorigin: ["feImage", "image", "script"],
  radius: ["feMorphology"],
  z: ["fePointLight", "feSpotLight"],
  specularConstant: ["feSpecularLighting"],
  specularExponent: ["feSpecularLighting", "feSpotLight"],
  limitingConeAngle: ["feSpotLight"],
  pointsAtX: ["feSpotLight"],
  pointsAtY: ["feSpotLight"],
  pointsAtZ: ["feSpotLight"],
  baseFrequency: ["feTurbulence"],
  numOctaves: ["feTurbulence"],
  seed: ["feTurbulence"],
  stitchTiles: ["feTurbulence"],
  filterRes: ["filter"],
  filterUnits: ["filter"],
  primitiveUnits: ["filter"],
  "horiz-adv-x": ["font", "glyph", "missing-glyph"],
  "horiz-origin-x": ["font"],
  "horiz-origin-y": ["font"],
  "vert-adv-y": ["font", "glyph", "missing-glyph"],
  "vert-origin-x": ["font", "glyph", "missing-glyph"],
  "vert-origin-y": ["font", "glyph", "missing-glyph"],
  "accent-height": ["font-face"],
  alphabetic: ["font-face"],
  ascent: ["font-face"],
  bbox: ["font-face"],
  "cap-height": ["font-face"],
  descent: ["font-face"],
  hanging: ["font-face"],
  ideographic: ["font-face"],
  mathematical: ["font-face"],
  "overline-position": ["font-face"],
  "overline-thickness": ["font-face"],
  "panose-1": ["font-face"],
  stemh: ["font-face"],
  stemv: ["font-face"],
  "strikethrough-position": ["font-face"],
  "strikethrough-thickness": ["font-face"],
  "underline-position": ["font-face"],
  "underline-thickness": ["font-face"],
  "unicode-range": ["font-face"],
  "units-per-em": ["font-face"],
  "v-alphabetic": ["font-face"],
  "v-hanging": ["font-face"],
  "v-ideographic": ["font-face"],
  "v-mathematical": ["font-face"],
  widths: ["font-face"],
  "x-height": ["font-face"],
  string: ["font-face-format"],
  "arabic-form": ["glyph"],
  d: ["glyph", "hatchpath", "missing-glyph", "path"],
  "glyph-name": ["glyph"],
  orientation: ["glyph"],
  unicode: ["glyph"],
  hatchContentUnits: ["hatch"],
  hatchUnits: ["hatch"],
  pitch: ["hatch"],
  g1: ["hkern", "vkern"],
  g2: ["hkern", "vkern"],
  k: ["hkern", "vkern"],
  u1: ["hkern", "vkern"],
  u2: ["hkern", "vkern"],
  x1: ["line", "linearGradient"],
  x2: ["line", "linearGradient"],
  y1: ["line", "linearGradient"],
  y2: ["line", "linearGradient"],
  gradientTransform: ["linearGradient", "radialGradient"],
  gradientUnits: ["linearGradient", "meshgradient", "radialGradient"],
  spreadMethod: ["linearGradient", "radialGradient"],
  defaultAction: ["listener"],
  event: ["listener"],
  handler: ["listener"],
  observer: ["listener"],
  phase: ["listener"],
  propagate: ["listener"],
  markerHeight: ["marker"],
  markerUnits: ["marker"],
  markerWidth: ["marker"],
  orient: ["marker"],
  refX: ["marker", "symbol"],
  refY: ["marker", "symbol"],
  viewBox: ["marker", "pattern", "svg", "symbol", "view"],
  maskContentUnits: ["mask"],
  maskUnits: ["mask"],
  patternContentUnits: ["pattern"],
  patternTransform: ["pattern"],
  patternUnits: ["pattern"],
  points: ["polygon", "polyline"],
  bandwidth: ["prefetch"],
  mediaCharacterEncoding: ["prefetch"],
  mediaContentEncodings: ["prefetch"],
  mediaSize: ["prefetch"],
  mediaTime: ["prefetch"],
  fr: ["radialGradient"],
  fx: ["radialGradient"],
  fy: ["radialGradient"],
  media: ["style"],
  title: ["style"],
  baseProfile: ["svg"],
  contentScriptType: ["svg"],
  contentStyleType: ["svg"],
  playbackOrder: ["svg"],
  playbackorder: ["svg"],
  snapshotTime: ["svg"],
  syncBehaviorDefault: ["svg"],
  syncToleranceDefault: ["svg"],
  timelineBegin: ["svg"],
  timelinebegin: ["svg"],
  version: ["svg"],
  zoomAndPan: ["svg", "view"],
  editable: ["text", "textArea"],
  lengthAdjust: ["text", "textPath", "tref", "tspan"],
  textLength: ["text", "textPath", "tref", "tspan"],
  method: ["textPath"],
  side: ["textPath"],
  spacing: ["textPath"],
  startOffset: ["textPath"],
  overlay: ["video"],
  transformBehavior: ["video"],
  viewTarget: ["view"],
};
module.exports.reactGlobalProps = [
  "dangerouslySetInnerHTML",
  "suppressContentEditableWarning",
  "suppressHydrationWarning",
  "classID",
  "keyParams",
  "autoSave",
];

module.exports.reactExtraPropsMap = {
  defaultChecked: ["input"],
  autoCorrect: ["input"],
  defaultValue: ["input", "textarea", "select"],
  value: ["input", "textarea", "select"],
  allowFullScreen: ["frame"],
  cellPadding: ["table"],
  cellSpacing: ["table"],
  controlsList: ["audio", "video"],
  frameBorder: ["frame"],
  inputMode: ["input"],
  marginHeight: ["iframe"],
  marginWidth: ["iframe"],
  mediaGroup: ["audio", "video"],
};
