module.exports.reactHtmlElementsToPropsMap = {
  a: [
    "download",
    "href",
    "hrefLang",
    "hreflang",
    "media",
    "ping",
    "rel",
    "shape",
    "formTarget",
    "target"
  ],
  abbr: [],
  acronym: [],
  address: [],
  applet: ["align", "alt", "code", "codebase"],
  area: [
    "alt",
    "coords",
    "download",
    "href",
    "hrefLang",
    "hreflang",
    "media",
    "ping",
    "rel",
    "shape",
    "formTarget",
    "target"
  ],
  article: [],
  aside: [],
  audio: [
    "autoPlay",
    "autoplay",
    "buffered",
    "controls",
    "crossOrigin",
    "crossorigin",
    "loop",
    "muted",
    "preload",
    "src",
    "controlsList",
    "mediaGroup"
  ],
  b: [],
  base: ["href", "formTarget", "target"],
  basefont: [],
  bdi: [],
  bdo: [],
  bgsound: ["loop"],
  big: [],
  blink: [],
  blockquote: ["cite"],
  body: [],
  br: [],
  button: [
    "autoFocus",
    "autofocus",
    "disabled",
    "form",
    "formAction",
    "formaction",
    "name",
    "type"
  ],
  canvas: ["height", "width"],
  caption: ["align"],
  center: [],
  cite: [],
  code: [],
  col: ["align", "span"],
  colgroup: ["align", "span"],
  command: ["checked", "disabled", "icon", "radioGroup", "radiogroup", "type"],
  content: [],
  data: [],
  datalist: [],
  dd: [],
  del: ["cite", "dateTime", "datetime"],
  details: ["open"],
  dfn: [],
  dialog: [],
  dir: [],
  div: [],
  dl: [],
  dt: [],
  element: [],
  em: [],
  embed: ["height", "src", "type", "width"],
  fieldset: ["disabled", "form", "name"],
  figcaption: [],
  figure: [],
  font: [],
  footer: [],
  form: [
    "accept",
    "acceptCharset",
    "accept-charset",
    "action",
    "autoComplete",
    "autocomplete",
    "formEncType",
    "enctype",
    "formMethod",
    "method",
    "name",
    "formNoValidate",
    "novalidate",
    "formTarget",
    "target"
  ],
  frame: ["allowFullScreen", "frameBorder"],
  frameset: [],
  h1: [],
  h2: [],
  h3: [],
  h4: [],
  h5: [],
  h6: [],
  head: [],
  header: [],
  hgroup: [],
  hr: ["align"],
  html: ["manifest"],
  i: [],
  iframe: [
    "align",
    "height",
    "name",
    "sandbox",
    "src",
    "srcDoc",
    "srcdoc",
    "width",
    "marginHeight",
    "marginWidth"
  ],
  image: [],
  img: [
    "align",
    "alt",
    "crossOrigin",
    "crossorigin",
    "height",
    "isMap",
    "ismap",
    "sizes",
    "src",
    "srcSet",
    "srcset",
    "useMap",
    "usemap",
    "width"
  ],
  input: [
    "accept",
    "alt",
    "autoComplete",
    "autocomplete",
    "autoFocus",
    "autofocus",
    "checked",
    "dirname",
    "disabled",
    "form",
    "formAction",
    "formaction",
    "height",
    "list",
    "max",
    "maxLength",
    "maxlength",
    "minLength",
    "minlength",
    "min",
    "multiple",
    "name",
    "pattern",
    "placeholder",
    "readOnly",
    "readonly",
    "required",
    "size",
    "src",
    "step",
    "type",
    "useMap",
    "usemap",
    "value",
    "width",
    "defaultChecked",
    "autoCorrect",
    "defaultValue",
    "inputMode"
  ],
  ins: ["cite", "dateTime", "datetime"],
  isindex: [],
  kbd: [],
  keygen: [
    "autoFocus",
    "autofocus",
    "challenge",
    "disabled",
    "form",
    "keyType",
    "keytype",
    "name"
  ],
  label: ["htmlFor", "for", "form"],
  legend: [],
  li: [],
  link: [
    "crossOrigin",
    "crossorigin",
    "href",
    "hrefLang",
    "hreflang",
    "integrity",
    "media",
    "rel",
    "sizes"
  ],
  listing: [],
  main: [],
  map: ["name"],
  mark: [],
  marquee: ["loop"],
  menu: ["type"],
  menuitem: [],
  meta: ["charSet", "charset", "content", "httpEquiv", "http-equiv", "name"],
  meter: ["form", "high", "low", "max", "min", "optimum"],
  multicol: [],
  nav: [],
  nextid: [],
  nobr: [],
  noembed: [],
  noframes: [],
  noscript: [],
  object: [
    "data",
    "form",
    "height",
    "name",
    "type",
    "useMap",
    "usemap",
    "width"
  ],
  ol: ["reversed", "start"],
  optgroup: ["disabled"],
  option: ["disabled", "selected"],
  output: ["htmlFor", "for", "form", "name"],
  p: [],
  param: ["name"],
  picture: [],
  plaintext: [],
  pre: [],
  progress: ["form", "max"],
  q: ["cite"],
  rp: [],
  rt: [],
  rtc: [],
  ruby: [],
  s: [],
  samp: [],
  script: [
    "async",
    "charSet",
    "charset",
    "crossOrigin",
    "crossorigin",
    "defer",
    "integrity",
    "language",
    "src",
    "type"
  ],
  section: [],
  select: [
    "autoFocus",
    "autofocus",
    "disabled",
    "form",
    "multiple",
    "name",
    "required",
    "size"
  ],
  shadow: [],
  slot: [],
  small: [],
  source: ["media", "sizes", "src", "type"],
  spacer: [],
  span: [],
  strike: [],
  strong: [],
  style: ["media", "scoped", "type"],
  sub: [],
  summary: [],
  sup: [],
  table: ["align", "summary", "cellPadding", "cellSpacing"],
  tbody: ["align"],
  td: ["align", "colSpan", "colspan", "headers", "rowSpan", "rowspan"],
  template: [],
  textarea: [
    "autoComplete",
    "autocomplete",
    "autoFocus",
    "autofocus",
    "cols",
    "dirname",
    "disabled",
    "form",
    "maxLength",
    "maxlength",
    "minLength",
    "minlength",
    "name",
    "placeholder",
    "readOnly",
    "readonly",
    "required",
    "rows",
    "value",
    "wrap",
    "defaultValue"
  ],
  tfoot: ["align"],
  th: ["align", "colSpan", "colspan", "headers", "rowSpan", "rowspan", "scope"],
  thead: ["align"],
  time: ["dateTime", "datetime"],
  title: [],
  tr: ["align"],
  track: ["default", "kind", "label", "src", "srcLang", "srclang"],
  tt: [],
  u: [],
  ul: [],
  var: [],
  video: [
    "autoPlay",
    "autoplay",
    "buffered",
    "controls",
    "crossOrigin",
    "crossorigin",
    "height",
    "loop",
    "muted",
    "poster",
    "preload",
    "src",
    "width",
    "controlsList",
    "mediaGroup"
  ],
  wbr: [],
  xmp: []
};
